services:

  #----- 01. docker socket proxy -----
  dockersocketproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    networks:
      npm_network:
        ipv4_address: 10.112.0.6
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped

  #----- 02. dozzle -----
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    networks:
      npm_network:
        ipv4_address: 10.112.0.7
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    labels:
      - com.centurylinklabs.watchtower.enable=true
      
  #----- 03. tugtainer -----
  tugtainer:
    ports:
      - 9412:80
    container_name: tugtainer
    environment:
      - TZ=Asia/Taipei
      - TUGTAINER_HOST_NAME=HomeSer_Tug
      - AGENT_SECRET=${SECRET}
      - AGENT_ALLOW_ENDPOINTS=http://172.16.8.1:9413
      #- NOTIFICATION_URLS=tgram://8928802877:AAGwjf2ZX6gsAmn8HHUbX8pX8mnU4qtycOM/1161371954
    networks:
      npm_network:
        ipv4_address: 10.112.0.9
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
    volumes:
      - /docker/tugtainer/tugtainer_data:/tugtainer
      - /var/run/docker.sock:/var/run/docker.sock:ro
    image: ghcr.io/quenary/tugtainer:1

  #----- 04. beszel server -----
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: http://172.16.8.2:8090
    networks:
      npm_network:
        ipv4_address: 10.112.0.12
    ports:
      - 8090:8090
    volumes:
      - /docker/beszel/beszel_data:/beszel_data
      - /docker/beszel/beszel_socket:/beszel_socket
    # healthcheck:
    #   test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
    #   interval: 120s
    #   start_period: 10s
    #   timeout: 5s

  #----- 05. beszel-agent -----
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    volumes:
      - /docker/beszel/beszel_agent_data:/var/lib/beszel-agent
      - /docker/beszel/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: 45876
      KEY: ${BESZEL_KEY}
      TOKEN: ${BESZEL_TOKEN}
      HUB_URL: http://beszel:8090
    # healthcheck:
    #   test: ['CMD', '/agent', 'health']
    #   interval: 120s
    networks:
      npm_network:
        ipv4_address: 10.112.0.13

networks:
  npm_network:
    external: true
